# url: 'http://delphi.org'
url: "https://delphiorg.github.io/"
title: 'The Podcast at Delphi.org'
tagline: 'About the Delphi programming language, tools, news, and community.'
description: 'Beyond the being the longest running podcast about Object Pascal and Delphi programming languages, tools, news, and community, this is also Jim McKeeth''s blog on other things programming and technology related.'
locale: en_us
# https://jekyll.github.io/jekyll-seo-tag/usage/
baseurl: ""

theme: jekyll-theme-hacker

timezone: America/Boise
permalink: /:title/
# paginate_path       : /page:num

# Where things are
# source              : .
# destination         : ./_site
# collections_dir     : .
# plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# sass:
#   sass_dir: _sass
# collections:
#   posts:
#     output          : true

# Handling Reading
safe                : false
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

incremental         : false
quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

whitelist           : []
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap    
  - jekyll-seo-tag
  - jekyll-tagging
  - jekyll-archives
  - jekyll-tagging-related_posts
kramdown:
  syntax_highlighter_opts:
    disable: true # Using Prism
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

exclude:
  - _scripts/
  - vendor/       
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/